name: Bug Report
description: Please describe your issue and fill out all the required fields.
title: 'Bug Report:'
labels: [bug]
assignees: JugieNoob
title: "Bug Report: "
body:

- type: markdown
  attributes:
    value: "### Please do not report issues from other engines. These must be reported in their respective repositories."
