name: Bug Report
description: Please describe your issue and fill out all the required fields.
title: 'Bug Report:'
labels: [bug]
assignees: JugieNoob
title: "Bug Report: "
body:
 - type: textarea
   attributes:
    label: Additional context

